// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using myCity.Api.Data;

#nullable disable

namespace myCity.Api.Migrations
{
    [DbContext(typeof(MyCityDbContext))]
    [Migration("20260417195734_CompleteDatabaseModel")]
    partial class CompleteDatabaseModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("myCity.Api.Entities.PublicBody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locality");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_public_bodies");

                    b.ToTable("public_bodies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Locality = "Gdańsk",
                            Name = "Miasto Gdańsk",
                            PhoneNumber = "58 524 45 00"
                        });
                });

            modelBuilder.Entity("myCity.Api.Entities.PublicBodyDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ExecutiveId")
                        .HasColumnType("integer")
                        .HasColumnName("executive_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PublicBodyId")
                        .HasColumnType("integer")
                        .HasColumnName("public_body_id");

                    b.HasKey("Id")
                        .HasName("pk_public_body_departments");

                    b.HasIndex("ExecutiveId")
                        .IsUnique()
                        .HasDatabaseName("ix_public_body_departments_executive_id");

                    b.HasIndex("PublicBodyId")
                        .HasDatabaseName("ix_public_body_departments_public_body_id");

                    b.ToTable("public_body_departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Zgłoszenia dotyczące lokalnych zagrożeń, niebezpiecznych znalezisk, dewastacji mienia publicznego oraz klęsk żywiołowych.",
                            ExecutiveId = 5,
                            Name = "Wydział Bezpieczeństwa i Zarządzania Kryzysowego",
                            PublicBodyId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Zgłoszenia dotyczące dziur w jezdni, uszkodzonych chodników, niedziałającej sygnalizacji świetlnej oraz brakujących lub zniszczonych znaków drogowych.",
                            ExecutiveId = 6,
                            Name = "Gdański Zarząd Dróg",
                            PublicBodyId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Zgłoszenia dotyczące powalonych drzew, połamanych gałęzi, niekoszonych trawników, uszkodzeń w parkach oraz zniszczonej małej architektury.",
                            ExecutiveId = 7,
                            Name = "Gdański Zarząd Zieleni",
                            PublicBodyId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Zgłoszenia dotyczące zanieczyszczenia powietrza (smog, spalanie śmieci), nielegalnych zrzutów ścieków do rzek oraz martwych zwierząt.",
                            ExecutiveId = 8,
                            Name = "Wydział Ekologii i Energetyki",
                            PublicBodyId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Zgłoszenia dotyczące dzikich wysypisk śmieci, przepełnionych śmietników, zanieczyszczenia ulic oraz problemów z wywozem odpadów.",
                            ExecutiveId = 9,
                            Name = "Wydział Gospodarki Komunalnej",
                            PublicBodyId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Zgłoszenia dotyczące awarii oświetlenia ulicznego, uszkodzonych barierek ochronnych oraz większych usterek infrastruktury miejskiej.",
                            ExecutiveId = 10,
                            Name = "Wydział Infrastruktury",
                            PublicBodyId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Zgłoszenia dotyczące nieprawidłowego parkowania, wraków pojazdów, zakłócania porządku publicznego oraz spożywania alkoholu w miejscach niedozwolonych.",
                            ExecutiveId = 11,
                            Name = "Straż Miejska",
                            PublicBodyId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Zgłoszenia dotyczące zniszczonych wiat przystankowych, rozbitych szyb, niedziałających biletomatów oraz uszkodzonych tablic informacji pasażerskiej.",
                            ExecutiveId = 12,
                            Name = "Zarząd Transportu Miejskiego",
                            PublicBodyId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Zgłoszenia dotyczące zapadniętych studzienek, brakujących włazów, awarii rur wodociągowych oraz podtopień infrastruktury drogowej.",
                            ExecutiveId = 13,
                            Name = "Gdańskie Wodociągi",
                            PublicBodyId = 1
                        });
                });

            modelBuilder.Entity("myCity.Api.Entities.StatusLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer")
                        .HasColumnName("creator_id");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_status_logs");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_status_logs_creator_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_status_logs_ticket_id");

                    b.ToTable("status_logs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Skierowano firmę Eko-Zieleń do usunięcia drzewa.",
                            CreatorId = 7,
                            TicketId = 2,
                            Timestamp = new DateTime(2026, 4, 2, 10, 15, 0, 0, DateTimeKind.Utc),
                            Title = "InProgress"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Wysłano serwis.",
                            CreatorId = 12,
                            TicketId = 3,
                            Timestamp = new DateTime(2026, 3, 29, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "InProgress"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Matryca została wymieniona. Biletomat sprawny.",
                            CreatorId = 25,
                            TicketId = 3,
                            Timestamp = new DateTime(2026, 3, 30, 16, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Resolved"
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Ekipa Wodociągów jest w drodze.",
                            CreatorId = 13,
                            TicketId = 4,
                            Timestamp = new DateTime(2026, 4, 5, 11, 20, 0, 0, DateTimeKind.Utc),
                            Title = "InProgress"
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Zlecono wymianę lampy.",
                            CreatorId = 10,
                            TicketId = 6,
                            Timestamp = new DateTime(2026, 3, 21, 8, 15, 0, 0, DateTimeKind.Utc),
                            Title = "InProgress"
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Latarnia znowu świeci.",
                            CreatorId = 23,
                            TicketId = 6,
                            Timestamp = new DateTime(2026, 3, 22, 12, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Resolved"
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Zgłoszono do natychmiastowego wywozu pozaharmonogramowego.",
                            CreatorId = 9,
                            TicketId = 7,
                            Timestamp = new DateTime(2026, 4, 5, 8, 0, 0, 0, DateTimeKind.Utc),
                            Title = "InProgress"
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Skierowano straż pożarną.",
                            CreatorId = 5,
                            TicketId = 9,
                            Timestamp = new DateTime(2026, 3, 25, 15, 30, 0, 0, DateTimeKind.Utc),
                            Title = "InProgress"
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Teren zabezpieczony, zagrożenie zneutralizowane.",
                            CreatorId = 5,
                            TicketId = 9,
                            Timestamp = new DateTime(2026, 3, 25, 18, 45, 0, 0, DateTimeKind.Utc),
                            Title = "Resolved"
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Ekipa DrogBud została powiadomiona.",
                            CreatorId = 6,
                            TicketId = 10,
                            Timestamp = new DateTime(2026, 4, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "InProgress"
                        });
                });

            modelBuilder.Entity("myCity.Api.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedContractorId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_contractor_id");

                    b.Property<int?>("AssignedOfficialId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_official_id");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("building_number");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_timestamp");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer")
                        .HasColumnName("creator_id");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_status");

                    b.Property<DateTime>("CurrentStatusTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_status_timestamp");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("district");

                    b.Property<string>("FlatNumber")
                        .HasColumnType("text")
                        .HasColumnName("flat_number");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postcode");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<int>("PublicBodyDepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("public_body_department_id");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("AssignedContractorId")
                        .HasDatabaseName("ix_tickets_assigned_contractor_id");

                    b.HasIndex("AssignedOfficialId")
                        .HasDatabaseName("ix_tickets_assigned_official_id");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_tickets_creator_id");

                    b.HasIndex("PublicBodyDepartmentId")
                        .HasDatabaseName("ix_tickets_public_body_department_id");

                    b.ToTable("tickets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingNumber = "120",
                            City = "Gdańsk",
                            CreationTimestamp = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = 1,
                            CurrentStatus = "New",
                            CurrentStatusTimestamp = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Na prawym pasie znajduje się głęboka wyrwa. Można uszkodzić zawieszenie.",
                            District = "Wrzeszcz",
                            Latitude = 54.378900m,
                            Longitude = 18.608700m,
                            PhotoUrl = "https://example.com/images/ticket1_a.jpg",
                            Postcode = "80-244",
                            Priority = "High",
                            PublicBodyDepartmentId = 2,
                            Street = "Grunwaldzka",
                            Title = "Głęboka dziura w jezdni"
                        },
                        new
                        {
                            Id = 2,
                            AssignedContractorId = 17,
                            AssignedOfficialId = 7,
                            BuildingNumber = "3",
                            City = "Gdańsk",
                            CreationTimestamp = new DateTime(2026, 4, 2, 8, 30, 0, 0, DateTimeKind.Utc),
                            CreatorId = 2,
                            CurrentStatus = "InProgress",
                            CurrentStatusTimestamp = new DateTime(2026, 4, 2, 10, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Po wczorajszej wichurze drzewo całkowicie blokuje ścieżkę rowerową.",
                            District = "Zaspa",
                            Latitude = 54.409800m,
                            Longitude = 18.601200m,
                            PhotoUrl = "https://example.com/images/ticket2.jpg",
                            Postcode = "80-462",
                            Priority = "High",
                            PublicBodyDepartmentId = 3,
                            Street = "Jana Pawła II",
                            Title = "Powalone drzewo na ścieżce"
                        },
                        new
                        {
                            Id = 3,
                            AssignedContractorId = 25,
                            AssignedOfficialId = 12,
                            BuildingNumber = "1",
                            City = "Gdańsk",
                            CreationTimestamp = new DateTime(2026, 3, 28, 14, 20, 0, 0, DateTimeKind.Utc),
                            CreatorId = 3,
                            CurrentStatus = "Resolved",
                            CurrentStatusTimestamp = new DateTime(2026, 3, 30, 16, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ktoś rozbił ekran, nie da się kupić biletu.",
                            District = "Śródmieście",
                            Latitude = 54.351200m,
                            Longitude = 18.646500m,
                            Note = "Wszędzie leży szkło, uważajcie",
                            PhotoUrl = "https://example.com/images/ticket3.jpg",
                            Postcode = "80-895",
                            Priority = "Normal",
                            PublicBodyDepartmentId = 8,
                            Street = "Podwale Grodzkie",
                            Title = "Zniszczony ekran biletomatu"
                        },
                        new
                        {
                            Id = 4,
                            AssignedContractorId = 26,
                            AssignedOfficialId = 13,
                            BuildingNumber = "15",
                            City = "Gdańsk",
                            CreationTimestamp = new DateTime(2026, 4, 5, 9, 10, 0, 0, DateTimeKind.Utc),
                            CreatorId = 4,
                            CurrentStatus = "InProgress",
                            CurrentStatusTimestamp = new DateTime(2026, 4, 5, 11, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Woda zalewa chodnik i śmierdzi.",
                            District = "Chełm",
                            Latitude = 54.346800m,
                            Longitude = 18.621400m,
                            PhotoUrl = "https://example.com/images/ticket4.jpg",
                            Postcode = "80-805",
                            Priority = "Critical",
                            PublicBodyDepartmentId = 9,
                            Street = "Cienista",
                            Title = "Wybiła studzienka"
                        },
                        new
                        {
                            Id = 5,
                            BuildingNumber = "10",
                            City = "Gdańsk",
                            CreationTimestamp = new DateTime(2026, 4, 6, 17, 45, 0, 0, DateTimeKind.Utc),
                            CreatorId = 1,
                            CurrentStatus = "New",
                            CurrentStatusTimestamp = new DateTime(2026, 4, 6, 17, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Stoi tu od pół roku, zajmuje miejsce, wyciekają z niego płyny.",
                            District = "Przymorze",
                            Latitude = 54.398100m,
                            Longitude = 18.589100m,
                            PhotoUrl = "https://example.com/images/ticket5_wrak.jpg",
                            Postcode = "80-398",
                            Priority = "Low",
                            PublicBodyDepartmentId = 7,
                            Street = "Obrońców Wybrzeża",
                            Title = "Porzucone auto bez tablic"
                        },
                        new
                        {
                            Id = 6,
                            AssignedContractorId = 23,
                            AssignedOfficialId = 10,
                            BuildingNumber = "18",
                            City = "Gdańsk",
                            CreationTimestamp = new DateTime(2026, 3, 20, 20, 10, 0, 0, DateTimeKind.Utc),
                            CreatorId = 2,
                            CurrentStatus = "Resolved",
                            CurrentStatusTimestamp = new DateTime(2026, 3, 22, 12, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Nie pali się latarnia bezpośrednio nad pasami, jest niebezpiecznie.",
                            District = "Stogi",
                            Latitude = 54.341500m,
                            Longitude = 18.660100m,
                            Postcode = "80-620",
                            Priority = "Normal",
                            PublicBodyDepartmentId = 6,
                            Street = "Nowotna",
                            Title = "Ciemno na przejściu dla pieszych"
                        },
                        new
                        {
                            Id = 7,
                            AssignedContractorId = 21,
                            AssignedOfficialId = 9,
                            BuildingNumber = "24",
                            City = "Gdańsk",
                            CreationTimestamp = new DateTime(2026, 4, 4, 13, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = 3,
                            CurrentStatus = "InProgress",
                            CurrentStatusTimestamp = new DateTime(2026, 4, 5, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pojemniki pełne od 3 dni, ptaki roznoszą śmieci po parku.",
                            District = "Oliwa",
                            Latitude = 54.415200m,
                            Longitude = 18.571400m,
                            PhotoUrl = "https://example.com/images/ticket7_smietnik.jpg",
                            Postcode = "80-320",
                            Priority = "Low",
                            PublicBodyDepartmentId = 5,
                            Street = "Opata Rybińskiego",
                            Title = "Śmieci wysypują się na wiatr"
                        },
                        new
                        {
                            Id = 8,
                            BuildingNumber = "312",
                            City = "Gdańsk",
                            CreationTimestamp = new DateTime(2026, 4, 7, 11, 20, 0, 0, DateTimeKind.Utc),
                            CreatorId = 4,
                            CurrentStatus = "New",
                            CurrentStatusTimestamp = new DateTime(2026, 4, 7, 11, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Na skraju lasu leży sterta worków z gruzem i stary sedes.",
                            District = "Jasień",
                            Latitude = 54.358100m,
                            Longitude = 18.530100m,
                            PhotoUrl = "https://example.com/images/ticket8_gruz.jpg",
                            Postcode = "80-125",
                            Priority = "Normal",
                            PublicBodyDepartmentId = 5,
                            Street = "Kartuska",
                            Title = "Ktoś wyrzucił gruz do lasu"
                        },
                        new
                        {
                            Id = 9,
                            AssignedContractorId = 14,
                            AssignedOfficialId = 5,
                            BuildingNumber = "5",
                            City = "Gdańsk",
                            CreationTimestamp = new DateTime(2026, 3, 25, 15, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = 1,
                            CurrentStatus = "Resolved",
                            CurrentStatusTimestamp = new DateTime(2026, 3, 25, 18, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Wielkie gniazdo na drzewie zaraz obok zjeżdżalni.",
                            District = "Orunia",
                            Latitude = 54.332100m,
                            Longitude = 18.614500m,
                            Note = "Uwaga dla służb: Szerszenie są wyjątkowo agresywne, wygląda na to, że ktoś rzucał w nie kamieniami!!!",
                            PhotoUrl = "https://example.com/images/ticket9_osy.jpg",
                            Postcode = "80-032",
                            Priority = "Critical",
                            PublicBodyDepartmentId = 1,
                            Street = "Gościnna",
                            Title = "Gniazdo szerszeni przy placu zabaw"
                        },
                        new
                        {
                            Id = 10,
                            AssignedContractorId = 16,
                            AssignedOfficialId = 6,
                            BuildingNumber = "1",
                            City = "Gdańsk",
                            CreationTimestamp = new DateTime(2026, 4, 6, 9, 30, 0, 0, DateTimeKind.Utc),
                            CreatorId = 2,
                            CurrentStatus = "InProgress",
                            CurrentStatusTimestamp = new DateTime(2026, 4, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Znak obrócił się na wietrze, kierowcy go nie widzą.",
                            District = "Śródmieście",
                            Latitude = 54.352800m,
                            Longitude = 18.640100m,
                            PhotoUrl = "https://example.com/images/ticket10_znak.jpg",
                            Postcode = "80-886",
                            Priority = "High",
                            PublicBodyDepartmentId = 2,
                            Street = "Targ Drzewny",
                            Title = "Znak STOP obrócony w złą stronę"
                        });
                });

            modelBuilder.Entity("myCity.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_timestamp");

                    b.Property<string>("Employer")
                        .HasColumnType("text")
                        .HasColumnName("employer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mail");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<int?>("PublicBodyDepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("public_body_department_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int?>("TrustScore")
                        .HasColumnType("integer")
                        .HasColumnName("trust_score");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("PublicBodyDepartmentId")
                        .HasDatabaseName("ix_users_public_body_department_id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2446),
                            FirstName = "Bartosz",
                            IsActive = true,
                            LastName = "Kujawa",
                            Mail = "bartosz.kujawa@mail.com",
                            Password = "zaq1@WSX",
                            PhoneNumber = "111222333",
                            Position = "",
                            Role = "Resident",
                            TrustScore = 100
                        },
                        new
                        {
                            Id = 2,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2459),
                            FirstName = "Oskar",
                            IsActive = true,
                            LastName = "Krenke",
                            Mail = "oskar.krenke@mail.com",
                            Password = "zaq1@WSX",
                            PhoneNumber = "123123123",
                            Position = "",
                            Role = "Resident",
                            TrustScore = 50
                        },
                        new
                        {
                            Id = 3,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2461),
                            FirstName = "Jakub",
                            IsActive = true,
                            LastName = "Markuszewski",
                            Mail = "jakub.markuszewski@mail.com",
                            Password = "zaq1@WSX",
                            PhoneNumber = "000000000",
                            Position = "",
                            Role = "Resident",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 4,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2464),
                            FirstName = "Kacper",
                            IsActive = true,
                            LastName = "Tubiak",
                            Mail = "kacper.tubiak@mail.com",
                            Password = "zaq1@WSX",
                            PhoneNumber = "111111111",
                            Position = "",
                            Role = "Resident",
                            TrustScore = -10
                        },
                        new
                        {
                            Id = 5,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2466),
                            FirstName = "Joanna",
                            IsActive = true,
                            LastName = "Pińska",
                            Mail = "joanna.pinska@gdansk.pl",
                            Password = "zaq1@WSX",
                            Position = "Dyrektor Wydziału",
                            Role = "Official",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 6,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2468),
                            FirstName = "Anna",
                            IsActive = true,
                            LastName = "Bobrowska",
                            Mail = "anna.bobrowska@gzdiz.gda.pl",
                            Password = "zaq1@WSX",
                            Position = "Dyrektor Zarządu Dróg",
                            Role = "Official",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 7,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2470),
                            FirstName = "Barbara",
                            IsActive = true,
                            LastName = "Tusk-Krajewska",
                            Mail = "barbara.tusk-krajewska@gzz.gda.pl",
                            Password = "zaq1@WSX",
                            Position = "Dyrektor Zarządu Zieleni",
                            Role = "Official",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 8,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2471),
                            FirstName = "Anna",
                            IsActive = true,
                            LastName = "Trzuskolas",
                            Mail = "anna.trzuskolas@gdansk.pl",
                            Password = "zaq1@WSX",
                            Position = "Dyrektor Wydziału",
                            Role = "Official",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 9,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2473),
                            FirstName = "Anna",
                            IsActive = true,
                            LastName = "Wołodźko",
                            Mail = "anna.wolodzko@gdansk.pl",
                            Password = "zaq1@WSX",
                            Position = "Dyrektor Wydziału",
                            Role = "Official",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 10,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2475),
                            FirstName = "Piotr",
                            IsActive = true,
                            LastName = "Spyra",
                            Mail = "wi@gdansk.gda.pl",
                            Password = "zaq1@WSX",
                            Position = "Dyrektor Wydziału",
                            Role = "Official",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 11,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2477),
                            FirstName = "Leszek",
                            IsActive = true,
                            LastName = "Walczak",
                            Mail = "leszek.walczak@strazmiejska.gda.pl",
                            Password = "zaq1@WSX",
                            Position = "Komendant Straży Miejskiej",
                            Role = "Official",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 12,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2478),
                            FirstName = "Łukasz",
                            IsActive = true,
                            LastName = "Kłos",
                            Mail = "lukasz.klos@ztm.gda.pl",
                            Password = "zaq1@WSX",
                            Position = "p.o. Dyrektora ZTM",
                            Role = "Official",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 13,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2480),
                            FirstName = "Danuta",
                            IsActive = true,
                            LastName = "Jarzembowska",
                            Mail = "danuta.jarzembowska@gdanskiewodociagi.pl",
                            Password = "zaq1@WSX",
                            Position = "Wiceprezes Zarządu",
                            Role = "Official",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 14,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2482),
                            Employer = "Miasto Gdańsk",
                            FirstName = "Jan",
                            IsActive = true,
                            LastName = "Kowalski",
                            Mail = "jan.kowalski@mycity.pl",
                            Password = "zaq1@WSX",
                            Position = "",
                            PublicBodyDepartmentId = 1,
                            Role = "Contractor",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 15,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2484),
                            Employer = "DrogBud Sp. z o.o.",
                            FirstName = "Piotr",
                            IsActive = true,
                            LastName = "Nowak",
                            Mail = "p.nowak@drogbud.pl",
                            Password = "zaq1@WSX",
                            Position = "",
                            PublicBodyDepartmentId = 2,
                            Role = "Contractor",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 16,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2486),
                            Employer = "Asfalt-Max",
                            FirstName = "Michał",
                            IsActive = true,
                            LastName = "Wiśniewski",
                            Mail = "m.wisniewski@asfalt-max.pl",
                            Password = "zaq1@WSX",
                            Position = "",
                            PublicBodyDepartmentId = 2,
                            Role = "Contractor",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 17,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2488),
                            Employer = "Eko-Zieleń",
                            FirstName = "Adam",
                            IsActive = true,
                            LastName = "Wójcik",
                            Mail = "a.wojcik@eko-zielen.pl",
                            Password = "zaq1@WSX",
                            Position = "",
                            PublicBodyDepartmentId = 3,
                            Role = "Contractor",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 18,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2490),
                            Employer = "Parki i Ogrody S.A.",
                            FirstName = "Tomasz",
                            IsActive = true,
                            LastName = "Kowalczyk",
                            Mail = "t.kowalczyk@parkiiogrody.pl",
                            Password = "zaq1@WSX",
                            Position = "",
                            PublicBodyDepartmentId = 3,
                            Role = "Contractor",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 19,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2492),
                            Employer = "Drzew-Serwis",
                            FirstName = "Krzysztof",
                            IsActive = true,
                            LastName = "Kamiński",
                            Mail = "k.kaminski@drzew-serwis.pl",
                            Password = "zaq1@WSX",
                            Position = "",
                            PublicBodyDepartmentId = 3,
                            Role = "Contractor",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 20,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2494),
                            Employer = "Eco-Tech",
                            FirstName = "Maciej",
                            IsActive = true,
                            LastName = "Lewandowski",
                            Mail = "m.lewandowski@eco-tech.pl",
                            Password = "zaq1@WSX",
                            Position = "",
                            PublicBodyDepartmentId = 4,
                            Role = "Contractor",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 21,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2496),
                            Employer = "Błysk-Trans",
                            FirstName = "Jakub",
                            IsActive = true,
                            LastName = "Zieliński",
                            Mail = "j.zielinski@blysk-trans.pl",
                            Password = "zaq1@WSX",
                            Position = "",
                            PublicBodyDepartmentId = 5,
                            Role = "Contractor",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 22,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2549),
                            Employer = "Czyste Miasto",
                            FirstName = "Szymon",
                            IsActive = true,
                            LastName = "Szymański",
                            Mail = "s.szymanski@czystemiasto.pl",
                            Password = "zaq1@WSX",
                            Position = "",
                            PublicBodyDepartmentId = 5,
                            Role = "Contractor",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 23,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2551),
                            Employer = "InfraBud",
                            FirstName = "Dawid",
                            IsActive = true,
                            LastName = "Woźniak",
                            Mail = "d.wozniak@infrabud.pl",
                            Password = "zaq1@WSX",
                            Position = "",
                            PublicBodyDepartmentId = 6,
                            Role = "Contractor",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 24,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2553),
                            Employer = "Miasto Gdańsk",
                            FirstName = "Kacper",
                            IsActive = true,
                            LastName = "Dąbrowski",
                            Mail = "k.dabrowski@mycity.pl",
                            Password = "zaq1@WSX",
                            Position = "",
                            PublicBodyDepartmentId = 7,
                            Role = "Contractor",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 25,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2555),
                            Employer = "Przystanek-Serwis",
                            FirstName = "Filip",
                            IsActive = true,
                            LastName = "Kozłowski",
                            Mail = "f.kozlowski@przystanek-serwis.pl",
                            Password = "zaq1@WSX",
                            Position = "",
                            PublicBodyDepartmentId = 8,
                            Role = "Contractor",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 26,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2557),
                            Employer = "Aqua-Bud",
                            FirstName = "Mateusz",
                            IsActive = true,
                            LastName = "Jankowski",
                            Mail = "m.jankowski@aqua-bud.pl",
                            Password = "zaq1@WSX",
                            Position = "",
                            PublicBodyDepartmentId = 9,
                            Role = "Contractor",
                            TrustScore = 0
                        },
                        new
                        {
                            Id = 27,
                            CreationTimestamp = new DateTime(2026, 4, 17, 19, 57, 32, 341, DateTimeKind.Utc).AddTicks(2559),
                            Employer = "Hydro-Naprawa",
                            FirstName = "Łukasz",
                            IsActive = true,
                            LastName = "Mazur",
                            Mail = "l.mazur@hydro-naprawa.pl",
                            Password = "zaq1@WSX",
                            Position = "",
                            PublicBodyDepartmentId = 9,
                            Role = "Contractor",
                            TrustScore = 0
                        });
                });

            modelBuilder.Entity("myCity.Api.Entities.PublicBodyDepartment", b =>
                {
                    b.HasOne("myCity.Api.Entities.User", "Executive")
                        .WithOne("ExecutiveDepartment")
                        .HasForeignKey("myCity.Api.Entities.PublicBodyDepartment", "ExecutiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_public_body_departments_users_executive_id");

                    b.HasOne("myCity.Api.Entities.PublicBody", "PublicBody")
                        .WithMany("PublicBodyDepartments")
                        .HasForeignKey("PublicBodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_public_body_departments_public_bodies_public_body_id");

                    b.Navigation("Executive");

                    b.Navigation("PublicBody");
                });

            modelBuilder.Entity("myCity.Api.Entities.StatusLog", b =>
                {
                    b.HasOne("myCity.Api.Entities.User", "User")
                        .WithMany("StatusLogs")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("fk_status_logs_users_creator_id");

                    b.HasOne("myCity.Api.Entities.Ticket", "Ticket")
                        .WithMany("StatusLogs")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_status_logs_tickets_ticket_id");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("myCity.Api.Entities.Ticket", b =>
                {
                    b.HasOne("myCity.Api.Entities.User", "Contractor")
                        .WithMany("AssignedTicketsToSolve")
                        .HasForeignKey("AssignedContractorId")
                        .HasConstraintName("fk_tickets_users_assigned_contractor_id");

                    b.HasOne("myCity.Api.Entities.User", "Official")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedOfficialId")
                        .HasConstraintName("fk_tickets_users_assigned_official_id");

                    b.HasOne("myCity.Api.Entities.User", "Creator")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_users_creator_id");

                    b.HasOne("myCity.Api.Entities.PublicBodyDepartment", "PublicBodyDepartment")
                        .WithMany("Tickets")
                        .HasForeignKey("PublicBodyDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_public_body_departments_public_body_department_id");

                    b.Navigation("Contractor");

                    b.Navigation("Creator");

                    b.Navigation("Official");

                    b.Navigation("PublicBodyDepartment");
                });

            modelBuilder.Entity("myCity.Api.Entities.User", b =>
                {
                    b.HasOne("myCity.Api.Entities.PublicBodyDepartment", "ContractorDepartment")
                        .WithMany("Contractors")
                        .HasForeignKey("PublicBodyDepartmentId")
                        .HasConstraintName("fk_users_public_body_departments_public_body_department_id");

                    b.Navigation("ContractorDepartment");
                });

            modelBuilder.Entity("myCity.Api.Entities.PublicBody", b =>
                {
                    b.Navigation("PublicBodyDepartments");
                });

            modelBuilder.Entity("myCity.Api.Entities.PublicBodyDepartment", b =>
                {
                    b.Navigation("Contractors");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("myCity.Api.Entities.Ticket", b =>
                {
                    b.Navigation("StatusLogs");
                });

            modelBuilder.Entity("myCity.Api.Entities.User", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("AssignedTicketsToSolve");

                    b.Navigation("CreatedTickets");

                    b.Navigation("ExecutiveDepartment");

                    b.Navigation("StatusLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
